Dockerfile-deploy
Dockerfile-dev

This will preinstall decidim docker's app dependencies in their `deploy` and `dev` variants so you'll save network requests when using them.

Preinstall common app dependencies

---

Dockerfile-deploy
Dockerfile-dev

Bundler 1.16.0 is still giving us problems. Now we're hitting bundler/bundler#6154 and bundler/bundler#6162.
Basically, `bundler 1.16.0` generates binstubs with the path to the originating `Gemfile` hardcoded. That means that we end up with a bundler binstub at `/usr/local/bundle/bin/bundle` containing `/tmp/decidim_app/Gemfile` hardcoded, but that folder no longer exists in the image.
This seems to not have propagated yet to decidim's builds, but it's easily reproducible by logging into a built container of the image and running `bundle`. It leads to:
```
[!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /tmp/decidim_app/Gemfile. Bundler cannot continue
```
You can also see a reproduction in my decidim fork (which had no base image caching, so hits the …

Don't preinstall dependencies for now

---

Dockerfile

Install yarn using `dpkg` instead of `npm`.

Install yarn using native method

---

Dockerfile-dev
Dockerfile-test
circle.yml

Adds a test image meant to be used on test-only environments like a CI server. It lacks other facilities usually useful when mounting local folders and expecting code reload & such.

Add test image

---

Dockerfile-dev
scripts/build_images.sh

This fixes a bug I introduced in #19 where I incorrectly specified the base image for the `Dockerfile-dev` image. It also removes an unsued argument.

Fix base image for dev image

---

Dockerfile-dev
README.md
scripts/entrypoint.sh

I don't think this was fixing anything but actually breaking things:
* This is just changing docker image defaults to a different folder, and
it's actually doing incorrectly because it's leaving `GEM_HOME` with the
default value, so when installing gems via `gem install <gem>`, they get
installed to a wrong location (this affects generator specs in decidim).
See
https://github.com/docker-library/ruby/blob/master/Dockerfile-debian.template#L69-L74.
* Also, the folder name is confusing, since gems get actually installed
to a "gems" subfolder inside this "gems" folder.
* Finally, I don't see how the linked issue relates to this.

Remove bad fix

---

Dockerfile-test

The problem in rubygems affecting our test suite that has already fixed in rubygems master and that we're currently workarounding in [our circleCI config](https://github.com/decidim/decidim/blob/8415b268fd94d4cd7bc752659827f852e5c3ce70/.circleci/config.yml#L60-L67), also happens when running tests locally through docker.
So I think it makes sense to move the fix to the base image until it is released.

Move rubygems patch to test image

---

Dockerfile
Dockerfile-test

Run `apt-get clean` after package installation. I guess this helps reducing image size. This was done is some places but not everywhere.

apt-get clean after package installation

---

Dockerfile
Dockerfile-test
scripts/build_images.sh

Rubygems 2.7.7 has been released so we no longer need to patch it.
This includes a tweak I added to the build scripts to test building against the new official images.

Remove unnecessary workaround

---

Dockerfile

Package managers are quite fragile to regressions and behavior changes
between versions. So I think it's better to lock images to a version we
know it's working fine.

Lock npm version again

---

circle.yml
scripts/build_images.sh
scripts/pull_images.sh
scripts/push_images.sh

Hi @josepjaume!
I noticed that new decidim applications are generated with a `Dockerfile` like this:
```dockerfile
FROM decidim/decidim:0.13.1
```
However, this tag does not exist. As a matter of fact, [no tags](http://dockerhub.com/r/decidim/decidim) like that one have been pushed since decidim 0.10.
By reading the scripts, I see that you're supposed to push to a branch with the same name as the release so that these tags get uploaded to dockerhub. It does not seem a priori a very handy workflow since you need to remember to create a new branch for each release.
What do you think about doing this when merging to master? Whatever tag was used to build the images, we'll push to latest and to that tag (and will overwrite the image if the tag was pushed before, which makes sense to me, I …

Bump base decidim & push released tags when merging to master

---

README.md

Fixes #7 
Adds some instructions to newbies on this repository.
I have a permissions problem generating the application, because the "stable" image doesn't have the entrypoint script. Maybe we also should add it to the official image?

Adds instructions on README.md

---

Dockerfile

After update to Decidim v0.22.0 the instructions here stopped working:
```bash
docker pull decidim/decidim:0.22.0
APP_NAME=HelloWorld
docker run -it -v "$(pwd):/code" decidim/decidim ${APP_NAME}
```
This gives an error regarding Bundler version:
> You must use Bundler 2 or greater with this lockfile.
This is because Docker Ruby:2.6.6 image comes with Bundler v1.17.2:
> $ docker run --rm -it ruby:2.6.6 bash
> root@874350c34b10:/# bundle --version
> Bundler version 1.17.2
So we need to update manually Bundler. This could be reverted in Ruby 2.7.1:
> $ docker run --rm -it ruby:2.7.1 bash
> root@c095b9cff2bc:/# bundle --version
> Bundler version 2.1.4

Bump Bundler version

---

Dockerfile
Dockerfile-test

Chrome and chrome driver versions have diverged.
This PR synchronizes both in the `Dockerfile-test`.

Syncrhonize chrome and chrome-driver versions

---

.github/workflows/on_push.yml
Dockerfile-dev
Dockerfile-test
README.md
dockerhub/Dockerfile-dev

Includes Dockerfile-test and Dockerfile-dev, closing #62. 
Updates the README to explain differences between Docker Hub and Github Container Registry images, and future plans to publish to both.
~~Temporarily changes the Github Action workflow to publish the images on pull request, to test the CI flow out. This commit will be reverted before opening the PR for review.~~
Can't be tested out while authentication isn't configured, which @tramuntanal and I will handle next week. I'm going to open the PR for review and create an issue for the authentication to keep track of its progress.
**Update** 
Now using decidim-bot to login into container registry.

Add remainder images to flow

---

.github/workflows/on_push.yml
Dockerfile
Dockerfile-test

Closes #63. Includes commits from #72 to expedite things.
~~Also depends on DOCKERHUB_PAT being correctly configured (currently it's being interpreted as a password by Docker Hub, instead of a token). cc @andreslucena~~
La DOCKERHUB_PAT ya está configurada 👍

Publish images to Docker Hub through new Github workflow

---

.github/workflows/dockerhub.yml
.github/workflows/github_registry.yml

Images are being pushed to both GHCR and Docker Hub with the same name, which means they end up missing the decidim/decidim repository on the latter (and so aren't published there).
This PR separates both flows and names images according to their registry repos in each one.

Fix image names for Docker Hub. 

---

scripts/entrypoint.sh

In phasing out the circleci flow we ended up also deleting decidim-dev's entrypoint.sh by mistake, and this fell through the cracks as we were no longer testing the builds on pull request, so we only found out after merging.
This PR adds the script back ~~, and temporarily tests the builds for Docker Hub on the pull_request, hence the draft status for the PR. Once the builds are confimed to be ok, I'll change it back to trigger on push, ans open the PR so it can be reviewed after xmas.~~, fixing the decidim-dev build and by consequence, the remainder builds that came after it.
Update: In the process I've also updated Docker Hub to have a separate repository for each image, as DH requires, so the images were finally pushed there.

Fix decidim-dev and Docker Hub publishing

---

Dockerfile-dev

Fixes https://github.com/decidim/docker/issues/76 by making entrypoint.sh executable

Fix entrypoint.sh permissions for the decidim-dev image

---

README.md
docker-compose.yml
scripts/hello-world.sh

And add documentation for it on the README, while overall improving the latter.
Addresses one of the major [user stories](https://github.com/decidim/docker/discussions/57) for Docker with Decidim, building on top of [the latest work done in fixing/renaming the available images](https://github.com/decidim/docker/discussions/67).
From the updated README:
> By cloning the repo and then running `docker-compose up`, you'll get a fully functional Decidim app complete with seed data, accessible at http://localhost:3000.
```bash
git clone git@github.com:decidim/docker.git decidim-docker
cd decidim-docker
docker-compose up
```
Lastly, this PR also tries to improve the clarity of the README a little bit.
(Took some inspiration from https://github.com/AjuntamentDeSabadell/decidim-sabadell/blob/master …

Add "Hello World" docker-compose.yml

---

.github/workflows/dockerhub.yml
.github/workflows/github_registry.yml

The [latest build](https://github.com/decidim/docker/runs/1887499929?check_suite_focus=true) didn't push the last 0.23.2 version tag, though it did correctly detect it:
```bash
echo ::set-output name=version::$(echo v0.23.2 | cut -c2-)
```
This adds the `--all-tags` option to `docker push`. ~~Testing it first on pull request, and so setting this to draft until it's confirmed to be working.~~
Confirmed working. Here are the builds:
https://github.com/decidim/docker/actions/runs/561383630
https://github.com/decidim/docker/actions/runs/561383631
And correctly tagged images:
https://github.com/orgs/decidim/packages/container/decidim/versions
https://hub.docker.com/r/decidim/decidim/tags?page=1&ordering=last_updated
I've switched the workflow back to `on.push` and the PR is ready to merge

Push all image tags on builds

---

scripts/hello-world.sh

It's breaking `docker-compose up`, since it expects the database to exist.
I have no idea how this was working when I tested it before 🤔

Remove rake db:environment:set statement from hello-world.sh

---

Dockerfile
Dockerfile-dev
Dockerfile-generator
Dockerfile-test

This week on Element/Matrix.org, someone mentioned that we weren't releasing docker images for the past 10 months. I've reported it yesterday at #93. This PR fixes it. 
The problem that we have is with the Node.js version that we were using an unsupported one. This can be checked by running the following command: 
```bash
docker build --no-cache --build-arg ruby_version=2.7.5 --build-arg decidim_version=0.26.0 --file Dockerfile-generator -t decidim-generator-v0.26.0 . 
```
<details>
<summary>Click to see full traceback</summary>
Sending build context to Docker daemon  315.4kB
Step 1/13 : ARG ruby_version=2.7.1
Step 2/13 : FROM ruby:${ruby_version}
---> e7c13114124c
Step 3/13 : LABEL maintainer="info@coditramuntana.com"
---> Running in a1b4a98284b4
Removing intermediate container …

Bump node version from 10 to 16
